import type { ActionDefinition } from "./actions.contract.js";

export const ACTION_DEFINITIONS: readonly ActionDefinition[] = [
  {
    id: "workbench.action.showPalette",
    label: "Find Action",
    category: "Workbench",
    shortcut: "⌘⇧A",
    keyMatcher: { key: "a", meta: true, shift: true },
  },
  {
    id: "workbench.action.findEverywhere",
    label: "Find Everywhere",
    category: "Workbench",
    shortcut: "⇧⇧",
  },
  {
    id: "workbench.action.openSettings",
    label: "Open Preferences",
    category: "Workbench",
    shortcut: "⌘,",
    keyMatcher: { key: ",", meta: true },
  },
  {
    id: "file.openRecent",
    label: "Recent Files…",
    category: "File",
    shortcut: "⌘E",
    keyMatcher: { key: "e", meta: true },
  },
  {
    id: "file.goToFile",
    label: "Go to File…",
    category: "File",
    shortcut: "⌘⇧O",
    keyMatcher: { key: "o", meta: true, shift: true },
  },
  {
    id: "workbench.action.toggleFileTree",
    label: "Toggle File Tree",
    category: "View",
    shortcut: "⌘1",
    keyMatcher: { key: "1", meta: true },
  },
  {
    id: "workbench.action.toggleRunPanel",
    label: "Toggle Run Panel",
    category: "View",
    shortcut: "⌘3",
    keyMatcher: { key: "3", meta: true },
  },
  {
    id: "workbench.action.toggleStructure",
    label: "Toggle Structure View",
    category: "View",
    shortcut: "⌘7",
    keyMatcher: { key: "7", meta: true },
  },
  {
    id: "workbench.action.toggleProblems",
    label: "Toggle Problems Panel",
    category: "View",
    shortcut: "⌘6",
    keyMatcher: { key: "6", meta: true },
  },
  {
    id: "workbench.action.toggleTodos",
    label: "Toggle TODO Panel",
    category: "View",
    shortcut: "⌘8",
    keyMatcher: { key: "8", meta: true },
  },
  {
    id: "workbench.action.toggleTerminal",
    label: "Toggle Terminal",
    category: "View",
    shortcut: "⌘⌥T",
    keyMatcher: { key: "t", meta: true, alt: true },
  },
  {
    id: "workbench.action.toggleZen",
    label: "Toggle Zen Mode",
    category: "View",
    shortcut: "⌘⌃F",
    keyMatcher: { key: "f", meta: true, ctrl: true },
  },
  {
    id: "editor.findInFile",
    label: "Find in File",
    category: "Edit",
    shortcut: "⌘F",
    keyMatcher: { key: "f", meta: true },
  },
  {
    id: "editor.findInPath",
    label: "Find in Path",
    category: "Edit",
    shortcut: "⌘⇧F",
    keyMatcher: { key: "f", meta: true, shift: true },
  },
  {
    id: "editor.gotoLine",
    label: "Go to Line…",
    category: "Edit",
    shortcut: "⌘L",
    keyMatcher: { key: "l", meta: true },
  },
  {
    id: "editor.formatDocument",
    label: "Reformat Document",
    category: "Edit",
    shortcut: "⌘⌥L",
    keyMatcher: { key: "l", meta: true, alt: true },
  },
  {
    id: "editor.nextTab",
    label: "Next Tab",
    category: "Navigate",
    shortcut: "⌘⌥]",
    keyMatcher: { key: "]", meta: true, alt: true },
  },
  {
    id: "editor.previousTab",
    label: "Previous Tab",
    category: "Navigate",
    shortcut: "⌘⌥[",
    keyMatcher: { key: "[", meta: true, alt: true },
  },
  {
    id: "editor.splitRight",
    label: "Split Right",
    category: "View",
    shortcut: "⌘⇧\\",
    keyMatcher: { key: "\\", meta: true, shift: true },
  },
  {
    id: "editor.closeSplit",
    label: "Close Split",
    category: "View",
  },
  {
    id: "navigate.back",
    label: "Back",
    category: "Navigate",
    shortcut: "⌘[",
    keyMatcher: { key: "[", meta: true },
  },
  {
    id: "navigate.forward",
    label: "Forward",
    category: "Navigate",
    shortcut: "⌘]",
    keyMatcher: { key: "]", meta: true },
  },
  {
    id: "navigate.recentLocations",
    label: "Recent Locations",
    category: "Navigate",
    shortcut: "⌘⇧E",
    keyMatcher: { key: "e", meta: true, shift: true },
  },
  {
    id: "run.editConfigurations",
    label: "Edit Run Configurations…",
    category: "Run",
  },
  {
    id: "file.save",
    label: "Save",
    category: "File",
    shortcut: "⌘S",
    keyMatcher: { key: "s", meta: true },
  },
  {
    id: "file.saveAll",
    label: "Save All",
    category: "File",
    shortcut: "⌘⌥S",
    keyMatcher: { key: "s", meta: true, alt: true },
  },
  {
    id: "file.close",
    label: "Close Tab",
    category: "File",
    shortcut: "⌘W",
    keyMatcher: { key: "w", meta: true },
  },
  {
    id: "file.reopenClosed",
    label: "Reopen Closed Tab",
    category: "File",
    shortcut: "⌘⇧T",
    keyMatcher: { key: "t", meta: true, shift: true },
  },
  {
    id: "file.closeOthers",
    label: "Close Other Tabs",
    category: "File",
  },
  {
    id: "file.closeToRight",
    label: "Close Tabs to the Right",
    category: "File",
  },
  {
    id: "file.closeAll",
    label: "Close All Tabs",
    category: "File",
  },
  {
    id: "bookmark.toggle",
    label: "Toggle Bookmark",
    category: "Navigate",
    shortcut: "⌥⌘B",
    keyMatcher: { key: "b", meta: true, alt: true },
  },
  {
    id: "bookmark.show",
    label: "Show Bookmarks",
    category: "Navigate",
    shortcut: "⌘⇧B",
    keyMatcher: { key: "b", meta: true, shift: true },
  },
  {
    id: "help.keymap",
    label: "Keymap Help",
    category: "Help",
    shortcut: "⌘/",
    keyMatcher: { key: "/", meta: true },
  },
  {
    id: "workspace.openFolder",
    label: "Open Folder…",
    category: "File",
    shortcut: "⌘O",
    keyMatcher: { key: "o", meta: true },
  },
  {
    id: "workspace.reloadThemes",
    label: "Reload Themes",
    category: "Theme",
  },
  {
    id: "workspace.openThemesDir",
    label: "Open Themes Folder",
    category: "Theme",
  },
  {
    id: "theme.clearOverrides",
    label: "Reset Theme Overrides",
    category: "Theme",
  },
  {
    id: "run.start",
    label: "Run Active Script",
    category: "Run",
    shortcut: "⌘⇧P",
    keyMatcher: { key: "p", meta: true, shift: true },
  },
  {
    id: "run.stop",
    label: "Stop Running Script",
    category: "Run",
  },
];
